import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { SignOutButton } from "@/components/SignOutButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}><body className="font-sans">>
      <header className="p-4 border-b flex items-center gap-4">
        <Link href="/">Home</Link>
        <Link href="/group-lessons">Group Lessons</Link>
        <Link href="/private-bookings">Private Bookings</Link>
        
        {/* ✅ make sure this is EXACTLY /whoami */}
        <Link href="/whoami" className="underline">Who am I</Link>
        <div className="ml-auto flex items-center gap-3">
          <Link className="underline" href="/auth/sign-in">Sign in</Link>
          <SignOutButton />
        </div>
      </header>
      {children}
    </body></html>
  )};